style_edition = "2024"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_macro_matchers = true
use_small_heuristics = "MAX"
match_block_trailing_comma = true
force_explicit_abi = false
newline_style = "Unix"
merge_derives = false
