{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferadb.fullname" . }}-secrets
  labels:
    {{- include "inferadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.auth.enabled }}
  {{- if .Values.secrets.jwksUrl }}
  INFERA__AUTH__JWKS_URL: {{ .Values.secrets.jwksUrl | quote }}
  {{- end }}
  {{- if .Values.config.auth.replayProtection }}
  {{- if .Values.secrets.redisUrl }}
  INFERA__AUTH__REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  INFERA__AUTH__REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.config.auth.oidc.enabled }}
  {{- if .Values.secrets.oidcClientSecret }}
  INFERA__AUTH__OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.config.store.backend "foundationdb" }}
  {{- if .Values.secrets.fdbClusterFile }}
  fdb.cluster: {{ .Values.secrets.fdbClusterFile | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additional }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
