{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferadb-engine.fullname" . }}-secrets
  labels:
    {{- include "inferadb-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.pem }}
  INFERADB__ENGINE__PEM: {{ .Values.secrets.pem | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additional }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
