apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferadb-engine.fullname" . }}
  labels:
    {{- include "inferadb-engine.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if and (eq .Values.service.type "NodePort") .Values.service.grpcNodePort }}
      nodePort: {{ .Values.service.grpcNodePort }}
      {{- end }}
    - port: {{ .Values.service.meshPort }}
      targetPort: mesh
      protocol: TCP
      name: mesh
      {{- if and (eq .Values.service.type "NodePort") .Values.service.meshNodePort }}
      nodePort: {{ .Values.service.meshNodePort }}
      {{- end }}
  selector:
    {{- include "inferadb-engine.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferadb-engine.fullname" . }}-headless
  labels:
    {{- include "inferadb-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.meshPort }}
      targetPort: mesh
      protocol: TCP
      name: mesh
  selector:
    {{- include "inferadb-engine.selectorLabels" . | nindent 4 }}
{{- end }}
