[package]
authors.workspace = true
description = "Shared FDB types for cross-service communication"
edition.workspace = true
license.workspace = true
name = "inferadb-engine-fdb-shared"
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
