apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inferadb-engine
  labels:
    app: inferadb-engine
    component: server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: inferadb-engine
      component: server
  unhealthyPodEvictionPolicy: IfHealthyBudget
