[package]
edition = "2021"
name = "inferadb-auth-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.inferadb-auth]
path = ".."

[[bin]]
doc = false
name = "jwt_decode"
path = "fuzz_targets/jwt_decode.rs"
test = false

[[bin]]
doc = false
name = "jwt_validation"
path = "fuzz_targets/jwt_validation.rs"
test = false

[[bin]]
doc = false
name = "bearer_extraction"
path = "fuzz_targets/bearer_extraction.rs"
test = false
