services:
  # Test runner with Rust environment
  # Note: Azure doesn't provide an official Key Vault emulator, so tests
  # will need to mock the service or skip integration tests
  test-runner:
    build:
      context: ../..
      dockerfile: docker/azure-integration-tests/Dockerfile
    container_name: inferadb-azure-test-runner
    environment:
      - AZURE_VAULT_URL=https://test-vault.vault.azure.net
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ../..:/workspace
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/workspace/target
    working_dir: /workspace
    networks:
      - azure-test-network
    command: /workspace/docker/azure-integration-tests/run-tests.sh

networks:
  azure-test-network:
    driver: bridge
    name: inferadb-azure-test-network

volumes:
  cargo-registry:
    name: inferadb-azure-cargo-registry
  cargo-git:
    name: inferadb-azure-cargo-git
  target-cache:
    name: inferadb-azure-target-cache
